### ISSUE TITLE
Trying to use UART but requires ETH

### ISSUE THREAD

**Issue by NemesisXB** [plasmapper/modbus-esp-cpp#5]
I am trying to use the pl_modbus component and I am using it using the UART. However, it requires esp_eth stuff and I am not using the ethernet.

**Comment by plasmapper** [comment]
I updated the pl_network component that is used by the pl_modbus component so that it excludes the ESP Ethernet code from compilation if it is not used, Please delete the "dependencies.lock" file and the "managed_components" directory from your project and try compiling again so that it downloads the updated version of the pl_network.

**Comment by NemesisXB** [comment]
Thanks. That fixed it.
